<Project>
  <!-- Общие настройки для всех проектов решения -->
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <!-- Позволяет запускать сборку на более новой среде выполнения (.NET 9, 10), если .NET 8 не установлен -->
    <RollForward>Major</RollForward>
    <InvariantGlobalization>false</InvariantGlobalization>
  </PropertyGroup>
</Project>
